version: '3.8'

services:
  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: extraccion-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: extraccion_db
      MYSQL_USER: extraccion_user
      MYSQL_PASSWORD: extraccion_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - extraccion-network

  # Aplicación principal
  app:
    build: .
    container_name: extraccion-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=extraccion_user
      - DB_PASSWORD=extraccion_pass
      - DB_NAME=extraccion_db
      - DB_PORT=3306
      - JWT_SECRET=tu_jwt_secret_muy_seguro_2024
      - PORT=3000
    depends_on:
      - mysql
    networks:
      - extraccion-network
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/backend/uploads

  # Nginx (opcional - para producción)
  nginx:
    image: nginx:alpine
    container_name: extraccion-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - app
    networks:
      - extraccion-network

volumes:
  mysql_data:

networks:
  extraccion-network:
    driver: bridge 